spring:
  jpa:
    show-sql: true
    hibernate:
      default_schema: public
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgres://mamzjpzqsewyjs:183f25ebbd8bb25da6c1e82aca8f55afcec3f37449329822772c9608678692d0@ec2-3-210-178-167.compute-1.amazonaws.com:5432/d7dt6c06gdl2qf?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driver-class-name: org.postgresql.Driver
    username: mamzjpzqsewyjs
    password: 183f25ebbd8bb25da6c1e82aca8f55afcec3f37449329822772c9608678692d0
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 5
